version: "3"

services:
  iab_db:
    image: mysql:latest
    container_name: iab_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iab
      MYSQL_USER: iab
      MYSQL_PASSWORD: iab
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  backend:
    container_name: iab-backend
    image: php-apache-iab
    build: './backend/'
    volumes:
      - ./backend/app:/var/www/html
    ports:
      - "8000:80"
volumes:
  dbdata: